#!/bin/bash
if [ "${LOGLEVEL}" == "" ]; then
  exec /sbin/setuser abc /usr/bin/python /config/RSScrawler.py --jd-pfad=/jd2 --log-level=$LOGLEVEL
else
  exec /sbin/setuser abc /usr/bin/python /config/RSScrawler.py --jd-pfad=/jd2 
fi
