#!/usr/bin/with-contenv bash

if [[ -v LOGLEVEL ]]; then
	LOGLEVEL=--log-level=$LOGLEVEL
fi

if [[ -v USER ]]; then
	USER=-jd-user=$USER
fi

if [[ -v PASS ]]; then
	PASS=--jd-pass=$PASS
fi

if [[ -v DEVICE ]]; then
	DEVICE=--log-level=$DEVICE
fi

 exec rsscrawler --docker $LOGLEVEL $USER $PASS $DEVICE

