#!/usr/bin/with-contenv bash

if [[ -v LOGLEVEL ]]; then
  exec s6-setuidgid abc python -u /config/RSScrawler.py --docker --log-level=$LOGLEVEL $PARAMETER
else
  exec s6-setuidgid abc python -u /config/RSScrawler.py --docker $PARAMETER
fi
