name: Build Image

on: 
  push:
  workflow_dispatch:
    inputs:
      version:
        default: 'false'
        required: false

env:
  ENDPOINT: "rix1337/docker-feedcrawler"

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.get-version.outputs.version }}
    steps:
      - id: get-version
        run: | 
          if [[ ${{ github.event.inputs.version }} == "false" ]]
          then
            echo "Grabbing latest feedcrawler version from pypi.org"
            VERSION=$(curl -Ls https://pypi.org/pypi/feedcrawler/json | jq -r .info.version)
          else
            echo "Using version from workflow_dispatch input"
            VERSION=${{ github.event.inputs.version }}
          fi
          echo $VERSION
          echo "::set-output name=version::$VERSION"
  build:
    runs-on: ubuntu-latest
    needs: version-check
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.DOCKERUSER }}"
          password: "${{ secrets.DOCKERPASS }}"
          image_name: "${{ env.ENDPOINT }}"
          image_tag: latest,${{needs.version-check.outputs.output}}
          stages_image_name: "rix1337/cache-feedcrawler-latest"
          
