name: Build Image

on: [push, workflow_dispatch]

env:
  ENDPOINT: "rix1337/docker-feedcrawler"

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.get-version.outputs.version }}
    steps:
      - id: get-version
        run: | 
          sudo apt-get update && apt-get install jq
          VERSION=$(curl -Ls https://pypi.org/pypi/feedcrawler/json | jq -r .info.version)
          echo $VERSION
          echo "::set-output name=version::$VERSION"
  build:
    runs-on: ubuntu-latest
    needs: version-check
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.DOCKERUSER }}"
          password: "${{ secrets.DOCKERPASS }}"
          image_name: "${{ env.ENDPOINT }}"
          image_tag: latest,${{needs.version-check.outputs.output}}
          stages_image_name: "rix1337/cache-feedcrawler-latest"
          
