#!/usr/bin/with-contenv bash

if [ ! -z "$REPO" ]
then
    [[ ! -d /config/.git ]] && (git clone $REPO /config)
else
    [[ ! -d /config/.git ]] && (git clone https://github.com/rix1337/RSScrawler.git /config)
fi

# change remote-url if REPO changed
cd /config
LOCAL_REPO = git config remote.origin.url
if [ "$LOCAL_REPO" != "$REPO" ]
then
    git remote set-url origin $REPO  
fi

# opt out for autoupdates
if [ "$NO_UPDATES" = true ]
then
    echo "skipping updates!"
    exit 0
fi

pip install cfscrape -U

cd /config
git fetch --all
if [ ! -z "$BRANCH" ]
then
    git reset --hard origin/$BRANCH
    git pull origin $BRANCH
else
    git reset --hard origin/master
    git pull origin master
fi
chown -R abc:abc /config/
chown -R abc:abc /jd2/folderwatch
