#!/usr/bin/with-contenv bash

if [ -z "$VERSION" ]; then
      pip install feedcrawler -U -q
else
      pip uninstall -y feedcrawler
      pip install feedcrawler=="$VERSION"
fi

chown -R abc:abc /config/
