#!/usr/bin/with-contenv bash

pip install cloudscraper -U -q

if [ -z "$VERSION" ]; then
      pip install feedcrawler -U -q
else
      pip uninstall -y feedcrawler
      pip install feedcrawler=="$VERSION"
fi

chown -R abc:abc /config/
chown -R abc:abc /jd2/folderwatch
